/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppFacturesRouteImport } from './routes/_app.factures'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppFacturesIdRouteImport } from './routes/_app.factures.$id'
import { Route as AppDevisIdRouteImport } from './routes/_app.devis.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturesRoute = AppFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturesIdRoute = AppFacturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFacturesRoute,
} as any)
const AppDevisIdRoute = AppDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/factures': typeof AppFacturesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/devis/$id': typeof AppDevisIdRoute
  '/factures/$id': typeof AppFacturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/factures': typeof AppFacturesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/devis/$id': typeof AppDevisIdRoute
  '/factures/$id': typeof AppFacturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/factures': typeof AppFacturesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/devis/$id': typeof AppDevisIdRoute
  '/_app/factures/$id': typeof AppFacturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/factures'
    | '/settings'
    | '/devis/$id'
    | '/factures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/factures'
    | '/settings'
    | '/devis/$id'
    | '/factures/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/factures'
    | '/_app/settings'
    | '/_app/devis/$id'
    | '/_app/factures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factures': {
      id: '/_app/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AppFacturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factures/$id': {
      id: '/_app/factures/$id'
      path: '/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof AppFacturesIdRouteImport
      parentRoute: typeof AppFacturesRoute
    }
    '/_app/devis/$id': {
      id: '/_app/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AppDevisIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppFacturesRouteChildren {
  AppFacturesIdRoute: typeof AppFacturesIdRoute
}

const AppFacturesRouteChildren: AppFacturesRouteChildren = {
  AppFacturesIdRoute: AppFacturesIdRoute,
}

const AppFacturesRouteWithChildren = AppFacturesRoute._addFileChildren(
  AppFacturesRouteChildren,
)

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFacturesRoute: typeof AppFacturesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppDevisIdRoute: typeof AppDevisIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFacturesRoute: AppFacturesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppDevisIdRoute: AppDevisIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
